### ISSUE TITLE
Final Capstone Project

### ISSUE THREAD

**Issue by Benedict-89** [ds4owd-001/project-Benedict-89#4]
@larnsce 

Please find attached my final capstone project. I worked on the Module 7 assignment, as you indicated earlier. Thank you

**Comment by larnsce** [comment]
Thank you, @Benedict-89. I will do a bit more detailed review to check for the all outlined elements, but here is some initial feedback:

YAML

 - Edit the affiliation to be your affiliaton
 - Either remove the ciation entry, or add your GitHub Pages websitelink here.
 - Remove `/cloud/project/` from the `bibliography` and `csl` entries
 
Code

- Edit all file paths and use the here::here() function, e.g.

```
borehole_data <- read_excel(here::here("data/raw/boreholes-Benedict-89.xlsx"))
```

The here::here() function helps to deal with file paths, which is why you can remove the cloud/project/ part. Now, if someone else cloned your repository to their computer, the code would also run without errors. For example, my computer does not have cloud/project as a path, but rather home/lars/. That's what here::here() takes care of.

**Comment by Benedict-89** [comment]
@larnsce 

Please, when I remove /cloud/project/ from the bibliography and csl entries and render, I get an error that those files cannot be found. But when I include them, it works. What should I do?

**Comment by larnsce** [comment]
Oh, I see. That was an oversight from my side. You will also need to move these two files into the `docs` folder. Then they are at the same folder level as your `index.qmd` report and the file path should work.

**Comment by Benedict-89** [comment]
I have fixed the problem now. I have created both files in the doc folder. Now, when I render, the pdf or html containing the report does not show, and there is no error message too

**Comment by Benedict-89** [comment]
Please, I have fixed the problem. Thank you. The report shows now

**Comment by larnsce** [comment]
Thanks, I will close this issue now.
